app/connectors/testOnly/TestOnlyDeparturesRouterConnector.scala, app/controllers/testOnly/TestOnlyDeparturesRouterController.scala, conf/testOnlyDoNotUseInAppConf.routes
Added route to allow us to submit an IE015
=> CTCTRADERS-877: Add routing for submitting declaration

app/viewModels/ViewArrivalMovements.scala, app/viewModels/ViewDepartureMovements.scala, test/base/ViewSpecBase.scala, test/viewModels/ViewArrivalMovementsSpec.scala, test/viewModels/ViewDepartureMovementsSpec.scala, test/views/ViewArrivalsSpec.scala, test/views/ViewDeparturesSpec.scala
Refactor to correct the ordering on display
=> CTCTRADERS 697 - resolve ordering on movement pages

app/controllers/TadPDFController.scala, app/viewModels/DepartureStatus.scala, conf/app.routes, conf/messages.en, conf/views/macros/table.njk, test/viewModels/DepartureStatusSpec.scala
Handle displaying following status:
_IE928 (declaration positive acknowledgement) - needed
IE045 (write off notification) -  needed_
Remove history links
Added placeholder tad link
=> CTCTRADERS-1128: Message journey - happy path (IE928 & IE045)

app/connectors/testOnly/TestOnlyDeparturesRouterConnector.scala, app/connectors/testOnly/TestOnlyRouterConnector.scala, app/controllers/testOnly/TestOnlyDeparturesRouterController.scala, app/controllers/testOnly/TestOnlyRouterController.scala
I know these are only in testOnly routes but if we don't need them lets get them removed.
=> Remove debug logs

app/config/FrontendAppConfig.scala, app/viewModels/DepartureStatus.scala, conf/application.conf, conf/messages.en, test/viewModels/DepartureStatusSpec.scala
Implemented cancel declaration link for IE015 (DeclarationSubmitted), IE028 (MrnAllocated), IE928 (PositiveAcknowledgement)
=> Ctctraders 2049 - User can start a cancel departure declaration

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_table.scss, conf/views/macros/table.njk
- replaced lists with tables
- added responsiveness to tables
- included the comments from [CTCTRADERS-1054](https://jira.tools.tax.service.gov.uk/browse/CTCTRADERS-1054)
=> CTCTRADERS-1655: Responsive table for view departures and view arrivals

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_pagination.scss, app/config/Module.scala, app/config/PaginationAppConfig.scala, app/connectors/ArrivalMovementConnector.scala, app/controllers/testOnly/ViewAllArrivalsController.scala, app/models/Arrivals.scala, app/viewModels/PaginationViewModel.scala, conf/application.conf, conf/testOnlyDoNotUseInAppConf.routes, conf/views/macros/pagination/macro.njk, conf/views/viewAllArrivals.njk, test/connectors/ArrivalMovementConnectorSpec.scala, test/controllers/ViewAllArrivalsControllerSpec.scala, test/controllers/WhatDoYouWantToDoControllerSpec.scala, test/controllers/arrival/ViewArrivalsControllerSpec.scala, test/models/ArrivalsSpec.scala, test/viewModels/PaginationViewModelSpec.scala, test/views/ViewAllArrivalsViewSpec.scala, test/views/behaviours/ViewBehaviours.scala
Reverts hmrc/manage-transit-movements-frontend#187
=> CTCTRADERS-2615: FIrst draft of pagination

conf/views/cancellationXmlNegativeAcknowledgement.njk, conf/views/departureXmlNegativeAcknowledgement.njk, conf/views/notFound.njk, conf/views/technicalDifficulties.njk, conf/views/unloadingRemarksXmlNegativeAcknowledgement.njk, conf/views/xmlNegativeAcknowledgement.njk
- Adding `rel="noopener noreferrer"` where we have `target="_blank"`
- Tidying up indentation
=> zap-issues

app/assets/stylesheets/components/_table.scss, app/controllers/arrival/ViewAllArrivalsController.scala, app/controllers/arrival/ViewArrivalsSearchResultsController.scala, app/controllers/departure/ViewAllDeparturesController.scala, conf/views/macros/showMovementsByDate.njk, test/controllers/arrival/ViewAllArrivalsControllerSpec.scala, test/controllers/arrival/ViewArrivalsSearchResultsControllerSpec.scala, test/controllers/departure/ViewDeparturesSearchResultsControllerSpec.scala
- Fixed unit tests that fail due to hour change
- Amended action link markup for `/view-departures` and `view-arrivals` pages (see screenshots)
=> Test and markup fixes

README.md, app/config/FrontendAppConfig.scala, app/config/Phase5.scala, conf/application.conf, test/config/FrontendAppConfigSpec.scala
- Each frontend now has a phase5 switch that can be overridden by service manager individually
=> CTCP-131 Add Phase5 switch for each frontend individually

app/views/components/MovementsTable.scala.html
=> CTCP-2986: Fix Status Tracking Table Alignment 

app/viewModels/P5/arrival/ArrivalStatusP5ViewModel.scala, conf/messages.en, test/viewModels/P5/ArrivalStatusP5ViewModelSpec.scala
=> Link fix (From View Errors to View errors)

app/controllers/departure/drafts/DeleteDraftDepartureYesNoController.scala, app/models/LocalReferenceNumber.scala, app/viewModels/drafts/AllDraftDeparturesViewModel.scala, conf/application.conf, conf/departures.drafts.routes, test/controllers/departure/drafts/DeleteDraftDepartureYesNoControllerSpec.scala, test/views/departure/drafts/DashboardViewSpec.scala
=> CTCP-3634 | Protect against HTML injection on LRN binding

app/controllers/arrivalP5/UnloadingRemarkWithFunctionalErrorsP5Controller.scala, app/views/arrivalP5/ArrivalNotificationWithFunctionalErrorsP5View.scala.html, app/views/arrivalP5/ArrivalNotificationWithoutFunctionalErrorsP5View.scala.html, app/views/arrivalP5/UnloadingRemarkWithFunctionalErrorsP5View.scala.html, app/views/arrivalP5/UnloadingRemarkWithoutFunctionalErrorsP5View.scala.html, app/views/components/HelpdeskLink.scala.html, app/views/departureP5/DepartureDeclarationErrorsP5View.scala.html, app/views/departureP5/RejectionMessageP5View.scala.html, app/views/departureP5/ReviewCancellationErrorsP5View.scala.html, app/views/departureP5/ReviewDepartureErrorsP5View.scala.html, test/controllers/arrivalP5/UnloadingRemarkWithFunctionalErrorsP5ControllerSpec.scala, test/controllers/departureP5/ReviewCancellationErrorsP5ControllerSpec.scala, test/views/arrivalP5/ArrivalNotificationWithFunctionalErrorsP5ViewSpec.scala, test/views/arrivalP5/ArrivalNotificationWithoutFunctionalErrorsP5ViewSpec.scala, test/views/arrivalP5/UnloadingRemarkWithFunctionalErrorsP5ViewSpec.scala, test/views/arrivalP5/ViewAllArrivalsP5ViewSpec.scala, test/views/behaviours/ViewBehaviours.scala, test/views/departureP5/DepartureDeclarationErrorsP5ViewSpec.scala, test/views/departureP5/RejectionMessageP5ViewSpec.scala, test/views/departureP5/ReviewCancellationErrorsP5ViewSpec.scala, test/views/departureP5/ReviewDepartureErrorsP5ViewSpec.scala
https://jira.tools.tax.service.gov.uk/browse/CTCP-5231
=> CTCP-5231: Added helpdesk link component.

app/assets/stylesheets/components/_table.scss, app/views/components/MovementsTable.scala.html, test/views/behaviours/MovementsTableViewBehaviours.scala
Table updated following guidelines here: https://design-system.service.gov.uk/components/table/
=> CTCP-5209: Responsive table not accessible

app/controllers/arrivalP5/ViewAllArrivalsP5Controller.scala, app/controllers/departureP5/ViewAllDeparturesP5Controller.scala, app/viewModels/P5/arrival/ViewAllArrivalMovementsP5ViewModel.scala, app/viewModels/P5/departure/ViewAllDepartureMovementsP5ViewModel.scala, app/views/arrivalP5/ViewAllArrivalsP5View.scala.html, app/views/departureP5/ViewAllDeparturesP5View.scala.html, conf/messages.en, test/controllers/arrival/ViewAllArrivalsP5ControllerSpec.scala, test/controllers/departure/ViewAllDeparturesP5ControllerSpec.scala, test/generators/ViewModelGenerators.scala, test/viewModels/P5/ViewAllArrivalMovementsP5ViewModelSpec.scala, test/viewModels/P5/ViewAllDepartureMovementsP5ViewModelSpec.scala, test/views/arrivalP5/ViewAllArrivalsP5ViewSpec.scala, test/views/departureP5/ViewAllDeparturesP5ViewSpec.scala
Ticket: [CTCP-5210](https://jira.tools.tax.service.gov.uk/browse/CTCP-5210)
=> CTCP-5210: Update Title/Heading when using search function

app/controllers/departureP5/GuaranteeRejectedP5Controller.scala, app/controllers/departureP5/ReviewCancellationErrorsP5Controller.scala, app/viewModels/P5/departure/DepartureStatusP5ViewModel.scala, app/views/departureP5/GuaranteeRejectedP5View.scala.html, app/views/departureP5/RejectionMessageP5View.scala.html, conf/departuresP5.routes, test/controllers/departureP5/GuaranteeRejectedP5ControllerSpec.scala, test/controllers/departureP5/RejectionMessageP5ControllerSpec.scala, test/views/behaviours/ViewBehaviours.scala, test/views/departureP5/GuaranteeRejectedP5ViewSpec.scala
- Identified a couple of endpoints which should be POSTs rather than GETs
- Fixed a styling issue (see screenshots)
- Added a TODO for another time
Before:
After:
=> Fixed styling issue.

app/controllers/actions/IdentifierAction.scala, conf/application-json-logger.xml
we can probably do something like a `retry` if that initial call to get enrolments is failing: https://gist.github.com/viktorklang/9414163
=> CTCP-5220: logs

app/connectors/ReferenceDataConnector.scala, app/models/referenceData/ControlType.scala, app/models/referenceData/FunctionalErrorWithDesc.scala, app/models/referenceData/RequestedDocumentType.scala, app/models/referenceData/referenceData.scala, app/services/ReferenceDataService.scala, app/services/services.scala, test/connectors/ReferenceDataConnectorSpec.scala, test/services/ReferenceDataServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/CTCP-5495
=> CTCP-5495: Refactor 

app/views/WhatDoYouWantToDoView.scala.html, app/views/components/Warning.scala.html, conf/messages.en, test/views/WhatDoYouWantToDoViewSpec.scala, test/views/behaviours/ViewBehaviours.scala
https://jira.tools.tax.service.gov.uk/browse/CTCP-5507
=> CTCP-5507: Adding warning text in P4 only.

app/views/WhatDoYouWantToDoView.scala.html, app/views/components/Warning.scala.html, conf/messages.en, test/views/WhatDoYouWantToDoViewSpec.scala
Before 4pm Friday 28th
Between 4pm Friday 28th June and 1pm Monday July 1st
After 1pm Monday July 1st
=> CTCP-5589: Updated warning text.

test/viewModels/P5/DepartureCancelledP5ViewModelSpec.scala, test/viewModels/P5/DepartureNotCancelledP5ViewModelSpec.scala
https://build.tax.service.gov.uk/job/Common%20Transit%20Convention%20Traders%20Phase%205/job/manage-transit-movements-frontend/248/consoleFull
=> Fixing flaky unit test.

app/controllers/WhatDoYouWantToDoController.scala, app/views/WhatDoYouWantToDoView.scala.html, conf/messages.en, test/base/AppWithDefaultMockFixtures.scala, test/controllers/WhatDoYouWantToDoControllerSpec.scala, test/views/WhatDoYouWantToDoViewSpec.scala, test/views/behaviours/ViewBehaviours.scala
=> Added warning text for users on legacy enrolment

app/controllers/DocumentController.scala, test/controllers/departureP5/TransitAccompanyingDocumentControllerSpec.scala
=> Removing WARN logs relating to CONTENT_TYPE and CONTENT_LENGTH.

app/connectors/ReferenceDataConnector.scala, app/models/QualifierOfIdentification.scala, app/services/ReferenceDataService.scala, app/utils/IncidentP5Helper.scala, conf/messages.en, test/connectors/ReferenceDataConnectorSpec.scala, test/helper/IncidentP5HelperSpec.scala, test/services/ReferenceDataServiceSpec.scala, test/viewModels/P5/IncidentP5ViewModelSpec.scala
=> CTCP-5575 Fix case and look up identification description

app/connectors/ReferenceDataConnector.scala, app/models/IdentificationType.scala, app/models/Nationality.scala, app/services/ReferenceDataService.scala, app/utils/IncidentP5Helper.scala, app/utils/IncidentP5TranshipmentHelper.scala, app/viewModels/P5/departure/IncidentP5ViewModel.scala, conf/messages.en, test/connectors/ReferenceDataConnectorSpec.scala, test/generators/MessagesModelGenerators.scala, test/helper/IncidentP5HelperSpec.scala, test/helper/IncidentP5TranshipmentHelperSpec.scala, test/services/ReferenceDataServiceSpec.scala, test/viewModels/P5/IncidentP5ViewModelSpec.scala
https://jira.tools.tax.service.gov.uk/browse/CTCP-5581
=> CTCP-5581 Display transhipment data

app/config/FrontendAppConfig.scala, app/controllers/arrivalP5/UnloadingRemarkWithFunctionalErrorsP5Controller.scala, app/controllers/arrivalP5/UnloadingRemarkWithoutFunctionalErrorsP5Controller.scala, app/viewModels/P5/arrival/ArrivalStatusP5ViewModel.scala, app/viewModels/P5/departure/DepartureStatusP5ViewModel.scala, app/views/arrivalP5/UnloadingRemarkWithFunctionalErrorsP5View.scala.html, app/views/arrivalP5/UnloadingRemarkWithoutFunctionalErrorsP5View.scala.html, conf/arrivalsP5.routes, conf/messages.en, test/controllers/arrivalP5/UnloadingRemarkWithFunctionalErrorsP5ControllerSpec.scala, test/controllers/arrivalP5/UnloadingRemarkWithoutFunctionalErrorsP5ControllerSpec.scala, test/viewModels/P5/ArrivalStatusP5ViewModelSpec.scala, test/viewModels/P5/DepartureStatusP5ViewModelSpec.scala, test/views/arrivalP5/UnloadingRemarkWithFunctionalErrorsP5ViewSpec.scala, test/views/arrivalP5/UnloadingRemarkWithoutFunctionalErrorsP5ViewSpec.scala
https://jira.tools.tax.service.gov.uk/browse/CTCP-5800
=> CTCP-5800: Displaying Make unloading remarks link on IE057 044 pages.

app/views/arrivalP5/ViewAllArrivalsP5View.scala.html, app/views/departureP5/ViewAllDeparturesP5View.scala.html, test/views/arrivalP5/ViewAllArrivalsP5ViewSpec.scala, test/views/departureP5/ViewAllDeparturesP5ViewSpec.scala
=> CTCP-4240: Add back link to search navigation

app/controllers/arrivalP5/ArrivalNotificationWithFunctionalErrorsP5Controller.scala, app/controllers/arrivalP5/UnloadingRemarkWithFunctionalErrorsP5Controller.scala, app/controllers/arrivalP5/ViewAllArrivalsP5Controller.scala, app/controllers/departureP5/RejectionMessageP5Controller.scala, app/controllers/departureP5/ReviewCancellationErrorsP5Controller.scala, app/controllers/departureP5/ReviewDepartureErrorsP5Controller.scala, app/controllers/departureP5/ViewAllDeparturesP5Controller.scala, app/controllers/departureP5/drafts/DashboardController.scala, app/viewModels/P5/arrival/ViewAllArrivalMovementsP5ViewModel.scala, app/viewModels/P5/departure/ViewAllDepartureMovementsP5ViewModel.scala, app/viewModels/drafts/AllDraftDeparturesViewModel.scala, app/viewModels/pagination/ListPaginationViewModel.scala, app/viewModels/pagination/PaginationViewModel.scala, app/views/arrivalP5/ViewAllArrivalsP5View.scala.html, app/views/components/DraftDeparturesTable.scala.html, app/views/departureP5/ViewAllDeparturesP5View.scala.html, conf/messages.en, test/generators/ViewModelGenerators.scala, test/viewModels/P5/ViewAllArrivalMovementsP5ViewModelSpec.scala, test/viewModels/P5/ViewAllDepartureMovementsP5ViewModelSpec.scala, test/viewModels/pagination/ListPaginationViewModelSpec.scala, test/views/arrivalP5/ViewAllArrivalsP5ViewSpec.scala, test/views/departureP5/ViewAllDeparturesP5ViewSpec.scala
See content change at the bottom of description https://jira.tools.tax.service.gov.uk/browse/CTCP-4229
=> CTCP-4229 Update hidden texts

app/controllers/arrivalP5/UnloadingPermissionController.scala, app/utils/SummaryListRowHelper.scala, build.sbt, project/plugins.sbt, test/connectors/MovementP5ConnectorSpec.scala, test/controllers/arrivalP5/UnloadingPermissionControllerSpec.scala, test/models/IdentificationTypeSpec.scala, test/models/IncidentCodeSpec.scala, test/models/NationalitySpec.scala, test/models/QualifierOfIdentificationSpec.scala, test/models/RichJsValueSpec.scala, test/models/departureP5/FunctionalErrorSpec.scala, test/models/departureP5/FunctionalErrorWithDescSpec.scala, test/models/departureP5/InvalidGuaranteeReasonSpec.scala, test/models/referenceData/ControlTypeSpec.scala, test/models/referenceData/RequestedDocumentTypeSpec.scala, test/services/MongoDraftDepartureServiceSpec.scala, test/utils/SummaryListRowHelperSpec.scala, test/viewModels/components/InputYesNoViewModelSpec.scala
https://jira.tools.tax.service.gov.uk/browse/CTCP-5941
=> CTCP-5941 Increase test coverage

app/controllers/departureP5/ViewAllDeparturesP5Controller.scala, app/models/departureP5/BusinessRejectionType.scala, app/models/departureP5/DepartureMovementAndMessage.scala, app/services/DepartureP5MessageService.scala, app/viewModels/P5/departure/DepartureStatusP5ViewModel.scala, test/generators/MessagesModelGenerators.scala, test/services/ArrivalP5MessageServiceSpec.scala, test/services/DepartureP5MessageServiceSpec.scala, test/viewModels/P5/DepartureStatusP5ViewModelSpec.scala
=> CTCP-5981: Display View Error link for IE56 against IE170

app/controllers/departureP5/ReviewPrelodgedDeclarationErrorsP5Controller.scala, app/viewModels/P5/departure/DepartureStatusP5ViewModel.scala, app/viewModels/P5/departure/ReviewPrelodgedDeclarationErrorsP5ViewModel.scala, app/views/departureP5/ReviewPrelodgedDeclarationErrorsP5View.scala.html, conf/departuresP5.routes, conf/messages.en, test/controllers/departureP5/ReviewPrelodgedDeclarationErrorsP5ControllerSpec.scala, test/viewModels/P5/DepartureStatusP5ViewModelSpec.scala, test/viewModels/ReviewPrelodgeDepartureErrorsP5ViewModelSpec.scala, test/viewModels/ReviewPrelodgedDeclarationErrorsP5ViewModelSpec.scala, test/views/departureP5/ReviewPrelodgedDeclarationErrorsP5ViewSpec.scala
=> CTCP-5982: Displaying errors when count of error >0

app/config/PhaseConfig.scala, app/controllers/departureP5/drafts/DashboardController.scala, app/models/Phase.scala, app/viewModels/drafts/AllDraftDeparturesViewModel.scala, app/views/departureP5/drafts/DashboardView.scala.html, conf/messages.en, test/base/SpecBase.scala, test/controllers/departureP5/drafts/DashboardControllerSpec.scala, test/generators/ModelGenerators.scala, test/generators/ViewModelGenerators.scala, test/viewModels/drafts/AllDraftDeparturesViewModelSpec.scala, test/views/departureP5/drafts/DashboardViewSpec.scala
https://jira.tools.tax.service.gov.uk/browse/CTCP-5985
=> CTCP-5985 Add paragraph for the cutover

conf/messages.en, test/viewModels/P5/departure/GoodsUnderControlP5ViewModelSpec.scala, test/views/departureP5/GoodsUnderControlP5RequestedDocumentsViewSpec.scala, test/views/departureP5/GoodsUnderControlP5ViewSpec.scala
=> CTCP-3254-1: Update paragraph for goods under control
